steps:
  # run tests
  - name: golang
    args: ["go", "test", "-v", "./..."]
  # build image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA", "."]
    #push to registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA"]
    # gke deployment
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=./k8s/deployment.yaml
      - --image=gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA
      - --location=us-east1
      - --cluster=toggs-app
